/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author ASUS TUF
 */
public class KalkulatorFrame extends javax.swing.JFrame {
    private boolean lanjut;
    private Kalkulator kal;
    private ArrayList<String> simpan;
    private boolean hasilSebelumnya = false;

    /**
     * Creates new form KalkulatorFrame
     */
    public KalkulatorFrame() {
        lanjut = true;
        kal = new Kalkulator();
        simpan = new ArrayList<String>();
        getContentPane().setBackground(new Color(214,217,223));
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        background = new javax.swing.JLabel();
        TampilanOP = new javax.swing.JTextField();
        tujuh = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        hapussemua = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        hasil1 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        Tampilan1 = new javax.swing.JTextField();
        tiga = new javax.swing.JButton();
        printinput = new javax.swing.JLabel();
        merek = new javax.swing.JLabel();
        watermark = new javax.swing.JLabel();
        kali = new javax.swing.JButton();
        TampilanOP1 = new javax.swing.JTextField();
        printinput1 = new javax.swing.JLabel();
        bagi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TampilanOP.setBackground(new java.awt.Color(0, 9, 19));
        TampilanOP.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        TampilanOP.setForeground(new java.awt.Color(102, 102, 255));
        TampilanOP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TampilanOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilanOPActionPerformed(evt);
            }
        });
        getContentPane().add(TampilanOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 30, 30));

        tujuh.setBackground(new java.awt.Color(0, 9, 19));
        tujuh.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tujuh.setForeground(new java.awt.Color(102, 102, 255));
        tujuh.setText("7");
        tujuh.setBorderPainted(false);
        tujuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tujuhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tujuhMouseExited(evt);
            }
        });
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        getContentPane().add(tujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 70));

        satu.setBackground(new java.awt.Color(0, 9, 19));
        satu.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        satu.setForeground(new java.awt.Color(102, 102, 255));
        satu.setText("1");
        satu.setBorderPainted(false);
        satu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                satuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                satuMouseExited(evt);
            }
        });
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 70, 70));

        dua.setBackground(new java.awt.Color(0, 9, 19));
        dua.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        dua.setForeground(new java.awt.Color(102, 102, 255));
        dua.setText("2");
        dua.setBorderPainted(false);
        dua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                duaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                duaMouseExited(evt);
            }
        });
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 70));

        empat.setBackground(new java.awt.Color(0, 9, 19));
        empat.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        empat.setForeground(new java.awt.Color(102, 102, 255));
        empat.setText("4");
        empat.setBorderPainted(false);
        empat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empatMouseExited(evt);
            }
        });
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        getContentPane().add(empat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 70));

        enam.setBackground(new java.awt.Color(0, 9, 19));
        enam.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        enam.setForeground(new java.awt.Color(102, 102, 255));
        enam.setText("6");
        enam.setBorderPainted(false);
        enam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enamMouseExited(evt);
            }
        });
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        getContentPane().add(enam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 70, 70));

        lima.setBackground(new java.awt.Color(0, 9, 19));
        lima.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lima.setForeground(new java.awt.Color(102, 102, 255));
        lima.setText("5");
        lima.setBorderPainted(false);
        lima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limaMouseExited(evt);
            }
        });
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        getContentPane().add(lima, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, 70));

        delapan.setBackground(new java.awt.Color(0, 9, 19));
        delapan.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        delapan.setForeground(new java.awt.Color(102, 102, 255));
        delapan.setText("8");
        delapan.setBorderPainted(false);
        delapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delapanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delapanMouseExited(evt);
            }
        });
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        getContentPane().add(delapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 70, 70));

        hapussemua.setBackground(new java.awt.Color(51, 51, 51));
        hapussemua.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        hapussemua.setForeground(new java.awt.Color(255, 255, 255));
        hapussemua.setText("C");
        hapussemua.setBorderPainted(false);
        hapussemua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapussemuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapussemuaMouseExited(evt);
            }
        });
        hapussemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapussemuaActionPerformed(evt);
            }
        });
        getContentPane().add(hapussemua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 70, 70));

        sembilan.setBackground(new java.awt.Color(0, 9, 19));
        sembilan.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        sembilan.setForeground(new java.awt.Color(102, 102, 255));
        sembilan.setText("9");
        sembilan.setBorderPainted(false);
        sembilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sembilanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sembilanMouseExited(evt);
            }
        });
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        getContentPane().add(sembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 70, 70));

        tambah.setBackground(new java.awt.Color(18, 0, 76));
        tambah.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("+");
        tambah.setBorderPainted(false);
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambahMouseExited(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 60));

        kurang.setBackground(new java.awt.Color(18, 0, 76));
        kurang.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        kurang.setForeground(new java.awt.Color(255, 255, 255));
        kurang.setText("-");
        kurang.setBorderPainted(false);
        kurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kurangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kurangMouseExited(evt);
            }
        });
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, 60));

        nol.setBackground(new java.awt.Color(0, 9, 19));
        nol.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        nol.setForeground(new java.awt.Color(102, 102, 255));
        nol.setText("0");
        nol.setBorderPainted(false);
        nol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nolMouseExited(evt);
            }
        });
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 170, 70));

        hasil1.setBackground(new java.awt.Color(255, 51, 0));
        hasil1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        hasil1.setForeground(new java.awt.Color(255, 255, 255));
        hasil1.setText("=");
        hasil1.setBorderPainted(false);
        hasil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hasil1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hasil1MouseExited(evt);
            }
        });
        hasil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil1ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 70, 70));

        hapus.setBackground(new java.awt.Color(25, 22, 22));
        hapus.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("⬅");
        hapus.setBorderPainted(false);
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hapusMouseExited(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 70, 70));

        Tampilan1.setBackground(new java.awt.Color(0, 9, 19));
        Tampilan1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Tampilan1.setForeground(new java.awt.Color(102, 102, 255));
        Tampilan1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Tampilan1.setText("0");
        Tampilan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tampilan1ActionPerformed(evt);
            }
        });
        getContentPane().add(Tampilan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 70));

        tiga.setBackground(new java.awt.Color(0, 9, 19));
        tiga.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tiga.setForeground(new java.awt.Color(102, 102, 255));
        tiga.setText("3");
        tiga.setBorderPainted(false);
        tiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tigaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tigaMouseExited(evt);
            }
        });
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 70, 70));

        printinput.setFont(new java.awt.Font("ROG Fonts", 0, 10)); // NOI18N
        printinput.setText("Input sebelumnya");
        getContentPane().add(printinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 130, 20));

        merek.setFont(new java.awt.Font("Auto Techno", 0, 14)); // NOI18N
        merek.setForeground(new java.awt.Color(51, 51, 51));
        merek.setText("FLAME - CHASER");
        getContentPane().add(merek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        watermark.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        watermark.setText("Creator Jimmy Maulana");
        getContentPane().add(watermark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 20));

        kali.setBackground(new java.awt.Color(18, 0, 76));
        kali.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        kali.setForeground(new java.awt.Color(255, 255, 255));
        kali.setText("X");
        kali.setBorderPainted(false);
        kali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kaliMouseExited(evt);
            }
        });
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, 60));

        TampilanOP1.setBackground(new java.awt.Color(0, 9, 19));
        TampilanOP1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        TampilanOP1.setForeground(new java.awt.Color(102, 102, 255));
        TampilanOP1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TampilanOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilanOP1ActionPerformed(evt);
            }
        });
        getContentPane().add(TampilanOP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 140, 30));

        printinput1.setFont(new java.awt.Font("ROG Fonts", 0, 12)); // NOI18N
        printinput1.setText("Operation :");
        getContentPane().add(printinput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 30));

        bagi.setBackground(new java.awt.Color(18, 0, 76));
        bagi.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        bagi.setForeground(new java.awt.Color(255, 255, 255));
        bagi.setText("÷");
        bagi.setBorderPainted(false);
        bagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bagiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bagiMouseExited(evt);
            }
        });
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, 60));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TampilanOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilanOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TampilanOPActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 2;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("2");
            simpan.add("2");
            lanjut = true;
        }
    }//GEN-LAST:event_duaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 4;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("4");
            simpan.add("4");
            lanjut = true;
        }
    }//GEN-LAST:event_empatActionPerformed

    private void hapussemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapussemuaActionPerformed
        // TODO add your handling code here:
        lanjut = false;
        Tampilan1.setText("0");
        TampilanOP.setText("");
        TampilanOP1.setText(" ");
        kal.reset();
    }//GEN-LAST:event_hapussemuaActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 1;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("1");
            simpan.add("1");
            lanjut = true;
        }
    }//GEN-LAST:event_satuActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 5;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("5");
            simpan.add("5");
            lanjut = true;
        }
    }//GEN-LAST:event_limaActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 8;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("8");
            simpan.add("8");
            lanjut = true;
        }
    }//GEN-LAST:event_delapanActionPerformed

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 6;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("6");
            simpan.add("6");
            lanjut = true;
        }
    }//GEN-LAST:event_enamActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 7;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("7");
            simpan.add("7");
            lanjut = true;
        }
    }//GEN-LAST:event_tujuhActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 9;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("9");
            simpan.add("9");
            lanjut = true;
        }
    }//GEN-LAST:event_sembilanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
    if (lanjut) {
        kal.tambah(angka);
    } else {
        kal.reset();
        kal.tambah(angka);
    }
    TampilanOP.setText("+");
    TampilanOP1.setText(Long.toString(angka));
    lanjut = false;
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
       long angka = Long.parseLong(Tampilan1.getText());
    if (lanjut) {
        kal.kurang(angka);
    } else {
        kal.reset();
        kal.kurang(angka);
    }
    TampilanOP.setText("-");
    TampilanOP1.setText(Long.toString(angka));
    lanjut = false;
    }//GEN-LAST:event_kurangActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 0;
            Tampilan1.setText(""+Nangka);
            
        }
        else{
            Tampilan1.setText("0");
            simpan.add("0");
            lanjut = true;
        }
        
    }//GEN-LAST:event_nolActionPerformed

    private void hasil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil1ActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
    if (TampilanOP.getText().equals("+")) {
        kal.tambah(angka);
    } else if (TampilanOP.getText().equals("-")) {
        kal.kurang(angka);
    } else if (TampilanOP.getText().equals("x")) {
        kal.kali(angka);
    } else if (TampilanOP.getText().equals("÷")) {
        kal.bagi(angka);
    }
        
    long hasil = kal.hasil();
    Tampilan1.setText(Long.toString(hasil));
    TampilanOP.setText("");
    TampilanOP1.setText(" ");
    kal.reset();
    lanjut = true;
    }//GEN-LAST:event_hasil1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String tampilan = Tampilan1.getText();
        if(tampilan.length() > 0) {
            if (tampilan.length() == 1) {
                tampilan = "0";  // reset tampilan ke 0 ketika hanya ada 1 karakter
            } else {
                tampilan = tampilan.substring(0, tampilan.length() - 1);
        }
        Tampilan1.setText(tampilan);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
        
        if(lanjut == true){
            long Nangka = angka * 10 + 3;
            Tampilan1.setText(""+Nangka);
        }
        else{
            Tampilan1.setText("3");
            simpan.add("3");
            lanjut = true;
        }
    }//GEN-LAST:event_tigaActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
    if (lanjut) {
        kal.kali(angka);
    } else {
        kal.reset();
        kal.kali(angka);
    }
    TampilanOP.setText("x");
    TampilanOP1.setText(Long.toString(angka));
    lanjut = false;
    }//GEN-LAST:event_kaliActionPerformed

    private void delapanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delapanMouseEntered
        // TODO add your handling code here:
        delapan.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_delapanMouseEntered

    private void delapanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delapanMouseExited
        // TODO add your handling code here:
        delapan.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_delapanMouseExited

    private void sembilanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sembilanMouseEntered
        // TODO add your handling code here:
        sembilan.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_sembilanMouseEntered

    private void sembilanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sembilanMouseExited
        // TODO add your handling code here:
        sembilan.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_sembilanMouseExited

    private void tujuhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tujuhMouseEntered
        // TODO add your handling code here:
        tujuh.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_tujuhMouseEntered

    private void tujuhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tujuhMouseExited
        // TODO add your handling code here:
        tujuh.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_tujuhMouseExited

    private void TampilanOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilanOP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TampilanOP1ActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        long angka = Long.parseLong(Tampilan1.getText());
    if (lanjut) {
        kal.bagi(angka);
    } else {
        kal.reset();
        kal.bagi(angka);
    }
    TampilanOP.setText("÷");
    TampilanOP1.setText(Long.toString(angka));
    lanjut = false;
    }//GEN-LAST:event_bagiActionPerformed

    private void Tampilan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tampilan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tampilan1ActionPerformed

    private void empatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empatMouseEntered
        // TODO add your handling code here:
        empat.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_empatMouseEntered

    private void limaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limaMouseEntered
        // TODO add your handling code here:
        lima.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_limaMouseEntered

    private void enamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enamMouseEntered
        // TODO add your handling code here:
        enam.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_enamMouseEntered

    private void satuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satuMouseEntered
        // TODO add your handling code here:
        satu.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_satuMouseEntered

    private void duaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duaMouseEntered
        // TODO add your handling code here:
        dua.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_duaMouseEntered

    private void tigaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tigaMouseEntered
        // TODO add your handling code here:
        tiga.setBackground(new Color(6,64,127));
    }//GEN-LAST:event_tigaMouseEntered

    private void nolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nolMouseEntered
        // TODO add your handling code here:
        nol.setBackground(new Color(193,112,196));
    }//GEN-LAST:event_nolMouseEntered

    private void empatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empatMouseExited
        // TODO add your handling code here:
         empat.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_empatMouseExited

    private void limaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limaMouseExited
        // TODO add your handling code here:
         lima.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_limaMouseExited

    private void enamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enamMouseExited
        // TODO add your handling code here:
         enam.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_enamMouseExited

    private void satuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satuMouseExited
        // TODO add your handling code here:
         satu.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_satuMouseExited

    private void duaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duaMouseExited
        // TODO add your handling code here:
         dua.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_duaMouseExited

    private void tigaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tigaMouseExited
        // TODO add your handling code here:
         tiga.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_tigaMouseExited

    private void nolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nolMouseExited
        // TODO add your handling code here:
         nol.setBackground(new Color(0,9,19));
    }//GEN-LAST:event_nolMouseExited

    private void hapussemuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapussemuaMouseExited
        // TODO add your handling code here:
        hapussemua.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_hapussemuaMouseExited

    private void hapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseEntered
        // TODO add your handling code here:
        hapus.setBackground(new Color(181, 176, 173));
    }//GEN-LAST:event_hapusMouseEntered

    private void hapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseExited
        // TODO add your handling code here:
         hapus.setBackground(new Color(25,22,21));
    }//GEN-LAST:event_hapusMouseExited

    private void hapussemuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapussemuaMouseEntered
        // TODO add your handling code here:
        hapussemua.setBackground(new Color(181, 176, 173));
    }//GEN-LAST:event_hapussemuaMouseEntered

    private void tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseExited
        // TODO add your handling code here:
        tambah.setBackground(new Color(18,0,76));
    }//GEN-LAST:event_tambahMouseExited

    private void tambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseEntered
        // TODO add your handling code here:
         tambah.setBackground(new Color(9,9,19));
    }//GEN-LAST:event_tambahMouseEntered

    private void kurangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kurangMouseEntered
        // TODO add your handling code here:
        kurang.setBackground(new Color(9,9,19));
    }//GEN-LAST:event_kurangMouseEntered

    private void kurangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kurangMouseExited
        // TODO add your handling code here:
        kurang.setBackground(new Color(18,0,76));
    }//GEN-LAST:event_kurangMouseExited

    private void kaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaliMouseEntered
        // TODO add your handling code here:
        kali.setBackground(new Color(9,9,19));
    }//GEN-LAST:event_kaliMouseEntered

    private void kaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaliMouseExited
        // TODO add your handling code here:
        kali.setBackground(new Color(18,0,76));
    }//GEN-LAST:event_kaliMouseExited

    private void bagiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagiMouseEntered
        // TODO add your handling code here:
        bagi.setBackground(new Color(9,9,19));
    }//GEN-LAST:event_bagiMouseEntered

    private void bagiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bagiMouseExited
        // TODO add your handling code here:
        bagi.setBackground(new Color(18,0,76));
    }//GEN-LAST:event_bagiMouseExited

    private void hasil1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasil1MouseEntered
        // TODO add your handling code here:
        hasil1.setBackground(new Color(212,34,0));
    }//GEN-LAST:event_hasil1MouseEntered

    private void hasil1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasil1MouseExited
        // TODO add your handling code here:
        hasil1.setBackground(new Color(255,51,0));
    }//GEN-LAST:event_hasil1MouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tampilan1;
    private javax.swing.JTextField TampilanOP;
    private javax.swing.JTextField TampilanOP1;
    private javax.swing.JLabel background;
    private javax.swing.JButton bagi;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapussemua;
    private javax.swing.JButton hasil1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JLabel merek;
    private javax.swing.JButton nol;
    private javax.swing.JLabel printinput;
    private javax.swing.JLabel printinput1;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    private javax.swing.JLabel watermark;
    // End of variables declaration//GEN-END:variables

    private Object getContenctPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
